[package]
name = "stack"
version = "0.2.0"
authors = ["arcnmx"]

description = "DSTs and arrays on the stack!"
keywords = ["smallvec", "array", "vec", "dst", "stack"]

documentation = "http://arcnmx.github.io/stack-rs/stack/"
repository = "https://github.com/arcnmx/stack-rs"
readme = "README.md"
license = "MIT"

[dependencies]
coalesce = "0.1"
nodrop = "0.1"
unreachable = "0.1"

[features]
unstable = []
